
name: damp_app_mvp
description: DAMP - Drink Monitor App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.13.1
  geolocator: ^10.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
